### ISSUE TITLE
Python 2 does not have f string

### ISSUE THREAD

**Issue by amirmazmi** [cmberryau/pypowerbi#1]
I tried using this library in python 2 but it fails due to the use of f-strings.
Install was done using pip install pypowerbi

Current workaround is to use future-fstrings package. Apply encoding cookie on top of each file in the package.

**Comment by cmberryau** [comment]
Good point! I will update this soon.

**Comment by cmberryau** [comment]
I've added fstring support and pushed 0.18 with it.

**Comment by tdaroly** [comment]
﻿Thanks Chris

I had one question if you do not mind. I am a beginner at python and was wondering can we also add rows to a dataset using your pypowerbi library?

**Comment by cmberryau** [comment]
No worries at all about being a beginner. You definitely can post rows! You can use datasets.post_rows on your client.

**Comment by tdaroly** [comment]
Thanks a lot for the prompt reply, I will try it tomorrow morning and let you know of the progress
