### ISSUE TITLE
Relationship

### ISSUE THREAD

**Issue by rouzbeh-afrasiabi** [cmberryau/pypowerbi#11]
First I would like to thank you for creating this package, saved me a lot of time. It seems currently relationship is not supported when posting a dataset. Will this feature be added in the future?

**Comment by rouzbeh-afrasiabi** [comment]
I was able to add relationships by using the same class structure as the one used for Table. You can remove this issue or flag it as solved.

**Comment by cmberryau** [comment]
Great to hear that you were able to add relationships! Would you like to create a PR so we can merge that?

**Comment by rouzbeh-afrasiabi** [comment]
I will create a PR as soon as I am done testing if the added code causes any issues with the functions available in datasets.py. Also, I am working on transforming pandas dataframes and csv files to Power BI datasets using pypower as base, would that be a feature that you would be interested in adding to the package?
