### ISSUE TITLE
Bug in datasets. delete_all_datasets

### ISSUE THREAD

**Issue by jogeiss** [cmberryau/pypowerbi#12]
Hi,
in datasets.delete_all_datasets the function detelete dataset is called with:
`self.delete_dataset(group_id, dataset.id)`

the definition of this function is 
`def delete_dataset(self, dataset_id, group_id=None):`

So I guess group_id and dataset_id are in the wrong order. It should be  `self.delete_dataset(dataset.id, group_id, )`
or
`self.delete_dataset(group_id = group_id, dataset_id = dataset.id)`

Best,
Johanna

**Comment by cmberryau** [comment]
Great, I will fix this in the next release. Thank you!
