### ISSUE TITLE
Unable to import if # -*- coding: future_fstrings -*- in first line

### ISSUE THREAD

**Issue by Invigor** [cmberryau/pypowerbi#14]
Hi,
Thanks for your great library.

My only issue was that I could not import while # -*- coding: future_fstrings -*- was in the first line of each file.

After I removed everything worked perfectly.

Using in Anaconda running Python 3.7.3.

Cheers,

Michael

**Comment by cmberryau** [comment]
Hi, thanks for the heads up. I don't use Anaconda so I haven't come across that issue yet.

**Comment by vazquezgz** [comment]
Hi Chris,

Many thanks for this library !!!

Quick question and sorry for the novice question.

I am trying to use your lib to update a json file.  how to use the encoder to get the data in your powerbi object dataset?

Many thanks,

G
