### ISSUE TITLE
Support for Dataflows

### ISSUE THREAD

**Issue by Invigor** [cmberryau/pypowerbi#21]
Hi Chris,

Any chance of adding support for Dataflows to the library?

Thanks,

Michael Stone

**Comment by cmberryau** [comment]
Hi Michael,

Absolutely - feel free to make the contribution if you would like.

Here is the documentation for the Dataflows REST API, which has a very similar pattern to the existing APIs the library supports.

https://docs.microsoft.com/en-us/rest/api/power-bi/dataflows

**Comment by Invigor** [comment]
Hi Chris,

Unfortunately my Python skills are not good enough, especially in terms of the classes stuff.

Cheers,

Michael
