### ISSUE TITLE
Upgrade version and upload to Pypi

### ISSUE THREAD

**Issue by octopyth** [cmberryau/pypowerbi#22]
Hey Chris, I get a bug that I see is fixed in the github repo, but not pushed to Pypi. Can you please upgrade/upload latest version to Pypi? Thanks!

**Comment by octopyth** [comment]
Hey Chris, one more thing. I am using the pypowerbi module with Azure Functions, which seem to be picky about how imports work (as it worked locally on windows, but not after deployment on linux). I am using python3.8 and had to remove all future string imports to make things work.
```python
# -*- coding: future_fstrings -*-
```

**Comment by cmberryau** [comment]
Hi mate, yes I will update the pypi version shortly - once I have a bit of time to test all the changes since the last build :)

**Comment by cmberryau** [comment]
Also - that doesn't surprise me with Azure functions! Some of their stuff can be a bit finnicky.

**Comment by cmberryau** [comment]
I've done this now!
