### ISSUE TITLE
Dataset refresh?

### ISSUE THREAD

**Issue by KimchaC** [cmberryau/pypowerbi#4]
First off all, this is an awesome project!

Do you have any plans to add refreshing of reports?

**Comment by cmberryau** [comment]
Hi there, thanks for the encouragement! Yes, that is definitely a planned feature. I will update this ticket once it is done.

**Comment by octopyth** [comment]
Hi, I am also interested in refreshing datasets - it is actually the only meaningful thing that I would use the API for, as data sources are not completely scheduled and refresh needs to be triggered manually upon ETL completion. Here is the API documentation: https://powerbi.microsoft.com/en-us/blog/announcing-data-refresh-apis-in-the-power-bi-service/ Looking forward an update soon.

**Comment by cmberryau** [comment]
I've just added that feature, give it a crack and see how it goes. I haven't really tested it yet.
