### ISSUE TITLE
End points road map

### ISSUE THREAD

**Issue by AlainPilon** [cmberryau/pypowerbi#6]
Hi,

do you have a road map of the end points you are planning to add? Are you aiming to cover all end points?

I was thinking about using the library to create/clone groups/workspace/apps and change their data sources.

**Comment by cmberryau** [comment]
Thanks for the inquiry! No real road map for now. I'm adding features based on my needs over time. It would be nice to cover all endpoints eventually. If you would like to add a feature, you are of course very welcome to do so.
