### ISSUE TITLE
Get Token request returned http error: 401

### ISSUE THREAD

**Issue by v0rt3x13** [cmberryau/pypowerbi#7]
adal.adal_error.AdalError: Get Token request returned http error: 401 and server response: {"error":"invalid_client"
,"error_description":"AADSTS70002: 
The request body must contain the following parameter: 'client_secret or client_assertion'.

I use code from example https://github.com/cmberryau/pypowerbi . 
I change nothing except credentials.
Where I should use "client_secret"?

p.s. Sorry for bad english

**Comment by cmberryau** [comment]
Looks like you might be having an issue with adal authentication. Ensure you're able to authenticate with your credentials normally, if that is the case I can investigate this further.

**Comment by DimaKudosh** [comment]
Have the same problem

**Comment by cmberryau** [comment]
This is an authentication issue, which is handled by the adal library. https://github.com/AzureAD/azure-activedirectory-library-for-python

**Comment by chhantyal** [comment]
FYI: I managed to get token by supplying client secret.

`token = context.acquire_token_with_client_credentials(resource_url, client_id=client_id, client_secret="sec")`

**Comment by Solitarystate** [comment]
> FYI: I was also facing this issue & I managed to get token by supplying client secret.
> 
> `token = context.acquire_token_with_client_credentials(resource_url, client_id=client_id, client_secret="sec")`

Hi. Could you advise what must be the resource URL. I am trying to write a python script that accesses the dataset refresh status and update a DB table with that information. Can we get the client_id and client_secret for a specific powerbi workspace inside Azure AD? Please advice.

**Comment by chhantyal** [comment]
Resource url is this: https://analysis.windows.net/powerbi/api

You can get client secret from Azure AD. You need to assign permissions & click Grant permissions explicitly to make it work.

**Comment by Solitarystate** [comment]
> Resource url is this: https://analysis.windows.net/powerbi/api
> 
> You can get client secret from Azure AD. You need to assign permissions & click Grant permissions explicitly to make it work.

Thanks for the response. Will check this!

**Comment by chhantyal** [comment]
Check this example for complete usage https://bitbucket.org/omnistream/powerbi-api-example/src/master/

**Comment by Solitarystate** [comment]
Brilliant document. Thanks for sharing. I am following that now. In my case I am writing a script to access the last dataset refresh time stamp . It isn’t going to be an app as such, it’s a tiny script. Will I still need to register an app? Or is there any other app id and app secret that I can fetch in AAD?. Just trying to put things in perspective. Appreciate advice

**Comment by Solitarystate** [comment]
> Check this example for complete usage https://bitbucket.org/omnistream/powerbi-api-example/src/master/

Brilliant document. Thanks for sharing. I am following that now. In my case I am writing a script to access the last dataset refresh time stamp . It isn’t going to be an app as such, it’s a tiny script. Will I still need to register an app? Or is there any other app id and app secret that I can fetch in AAD?. Just trying to put things in perspective. Appreciate advice

**Comment by Solitarystate** [comment]
> Check this example for complete usage https://bitbucket.org/omnistream/powerbi-api-example/src/master/

Thanks for your help. I completed the script. I registered my app as Native app and client secret wasn't necessary to get the access token.
